// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whtdnzigerjvdfmzbwgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndodGRuemlnZXJqdmRmbXpid2dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NTkzODUsImV4cCI6MjA1ODMzNTM4NX0.Xo-6wIvXtT-ri9wNXPJqQN0X3Hqr1hE-cvgJkmVoDMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);